import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@mantine/core/styles.css";
// import "mantine-datatable/styles.css";
import '@mantine/charts/styles.css';
import '@mantine/dates/styles.css';
import { ModalsProvider } from "@mantine/modals";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";

import "./globals.css";
import { Providers } from "@/store/providers";
import ProtectedRoute from "@/utils/authentication";
import { Notifications } from "@mantine/notifications";
import "@mantine/dates/styles.css";
import '@mantine/notifications/styles.css';
import { NavbarDemo } from "./components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Store Management",
  description: "Generated by create next app",
};

const violetBrand = [
  '#F5E0FC',
  '#E6B6F8',
  '#D68BF4',
  '#C661F0',
  '#B636EC',
  '#9F12E0',
  '#8C10C5',
  '#7910AA',
  '#660F8F',
  '#520D74',
] as const;



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get the current pathname
 // Adjust this if your login route is different

  return (
    <html lang="en">
      <body className='bg-[#f5f5f5]'>
        <MantineProvider 
          defaultColorScheme="light"   
          theme={{
            colors: {
              violetBrand,
            },
            primaryColor: 'violetBrand',
          }}
        >
          <ModalsProvider>
            <Providers>
             
              {children}
            </Providers>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}